name: Deploy to Heroku

on:
  push:
    branches:
      - main  # or your main branch name

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Git user
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      - name: Deploy to Heroku
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
          HEROKU_APP_NAME: ${{ secrets.HEROKU_APP_NAME }}
          HEROKU_EMAIL: ${{ secrets.HEROKU_EMAIL }}
        run: |
          cd recommend  # Update this line to point to your subdirectory
          git init
          heroku git:remote -a $HEROKU_APP_NAME
          git add .
          git commit -m "Deploying subdirectory"
          git push --force heroku master  # Ensure this matches the main branch on Heroku
